version: "3.9"

services:
  db:
    image: postgres:15
    container_name: wallet-postgres
    restart: unless-stopped
    env_file:
      - .env
    environment:
      # Valores padrão (serão sobrescritos pelo .env se presente)
      POSTGRES_USER: ${POSTGRES_USER:-wallet_user}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-wallet_pass}
      POSTGRES_DB: ${POSTGRES_DB:-wallet_db}
    ports:
      - "${HOST_DB_PORT:-5432}:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
