"""add description to wallets

Revision ID: 18ed21ec2f41
Revises: 00f70f2fe3cb
Create Date: 2025-09-27 00:51:29.972476

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '18ed21ec2f41'
down_revision: Union[str, Sequence[str], None] = '00f70f2fe3cb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('wallets', sa.Column('description', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('wallets', 'description')
    # ### end Alembic commands ###
